### ISSUE TITLE
Anyone going to update, fix bugs or it's a dead end (still better then 6.1) ? :D

### ISSUE THREAD

**Issue by mk89pwnz** [cool7su/Broken_Clashbot#31]
Did not found where to post some msg, so posted here :/

**Comment by xtcian** [comment]
Care to share 6.1?  :) :)

**Comment by mk89pwnz** [comment]
I'am not VIP so i didn't test it, but VIP ppl where coming back to this and saying it's better :)

**Comment by xtcian** [comment]
I have 6.0.2. Its stable as a rock... but lack some of this version
feature's. .. would like to merge the 2... dont care much for the skins....
after all.. its not like I am sitting staring at the acreen anyway lol (of
course I do when I am bored hahaha)

There is however a few new features I was thinking of... will try to figure
out how the helll to make them.. then keep you guys up to date... I think
this version is going to become the best and most popular due to everyone
contributing

**Comment by NotUsed** [comment]
yes, much better version, 6.1 cant view source as its just exe and dll file

I bought premium version and i got banned just for asking to share true story about code

**Comment by xtcian** [comment]
It would be nice to have a look tho...just to see what the fuzz is about

**Comment by ckodex** [comment]
Yeah, looks like broken has dropped off completely which doesn't surprise me.  I've been thinking about some things..I'd be all about contributing some code but honestly there's not many issues posted here.  We should all write our ideas so we can then argue about the direction of what we should add.

**Comment by codebroken** [comment]
I've not disappeared, I'll fix as necessary just don't have much time, but that's what opensource is all about.

**Comment by codebroken** [comment]
Made a better place for simple discussions.  Didn't want to setup a whole forum where people have to register, just a simple chatroom: http://www.e-chat.co/room/77641
